# Generated by Django 4.1.3 on 2022-11-14 16:31

from django.db import migrations, models
import studentapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Age', models.IntegerField(validators=[studentapp.validators.age_validation])),
                ('Class', models.CharField(choices=[('---', '---'), ('+1', '+1'), ('+2', '+2')], default='---', max_length=40)),
                ('Description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
